// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackFW.proto

package protopacks;

public final class PackFW {
  private PackFW() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackHeaderInOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protopacks.PackHeaderIn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool serverRead = 1;</code>
     */
    boolean getServerRead();

    /**
     * <code>string locKey = 2;</code>
     */
    java.lang.String getLocKey();
    /**
     * <code>string locKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocKeyBytes();

    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    java.util.List<java.lang.Integer> getSendToIDsList();
    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    int getSendToIDsCount();
    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    int getSendToIDs(int index);

    /**
     * <code>uint32 dataSize = 4;</code>
     */
    int getDataSize();
  }
  /**
   * Protobuf type {@code protopacks.PackHeaderIn}
   */
  public  static final class PackHeaderIn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protopacks.PackHeaderIn)
      PackHeaderInOrBuilder {
    // Use PackHeaderIn.newBuilder() to construct.
    private PackHeaderIn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackHeaderIn() {
      serverRead_ = false;
      locKey_ = "";
      sendToIDs_ = java.util.Collections.emptyList();
      dataSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PackHeaderIn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverRead_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              locKey_ = s;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendToIDs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendToIDs_.add(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sendToIDs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sendToIDs_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {

              dataSize_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendToIDs_ = java.util.Collections.unmodifiableList(sendToIDs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protopacks.PackFW.internal_static_protopacks_PackHeaderIn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protopacks.PackFW.internal_static_protopacks_PackHeaderIn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protopacks.PackFW.PackHeaderIn.class, protopacks.PackFW.PackHeaderIn.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERREAD_FIELD_NUMBER = 1;
    private boolean serverRead_;
    /**
     * <code>bool serverRead = 1;</code>
     */
    public boolean getServerRead() {
      return serverRead_;
    }

    public static final int LOCKEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object locKey_;
    /**
     * <code>string locKey = 2;</code>
     */
    public java.lang.String getLocKey() {
      java.lang.Object ref = locKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locKey_ = s;
        return s;
      }
    }
    /**
     * <code>string locKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocKeyBytes() {
      java.lang.Object ref = locKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTOIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> sendToIDs_;
    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getSendToIDsList() {
      return sendToIDs_;
    }
    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    public int getSendToIDsCount() {
      return sendToIDs_.size();
    }
    /**
     * <code>repeated uint32 sendToIDs = 3;</code>
     */
    public int getSendToIDs(int index) {
      return sendToIDs_.get(index);
    }
    private int sendToIDsMemoizedSerializedSize = -1;

    public static final int DATASIZE_FIELD_NUMBER = 4;
    private int dataSize_;
    /**
     * <code>uint32 dataSize = 4;</code>
     */
    public int getDataSize() {
      return dataSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (serverRead_ != false) {
        output.writeBool(1, serverRead_);
      }
      if (!getLocKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, locKey_);
      }
      if (getSendToIDsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(sendToIDsMemoizedSerializedSize);
      }
      for (int i = 0; i < sendToIDs_.size(); i++) {
        output.writeUInt32NoTag(sendToIDs_.get(i));
      }
      if (dataSize_ != 0) {
        output.writeUInt32(4, dataSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverRead_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, serverRead_);
      }
      if (!getLocKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, locKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sendToIDs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(sendToIDs_.get(i));
        }
        size += dataSize;
        if (!getSendToIDsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sendToIDsMemoizedSerializedSize = dataSize;
      }
      if (dataSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, dataSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protopacks.PackFW.PackHeaderIn)) {
        return super.equals(obj);
      }
      protopacks.PackFW.PackHeaderIn other = (protopacks.PackFW.PackHeaderIn) obj;

      boolean result = true;
      result = result && (getServerRead()
          == other.getServerRead());
      result = result && getLocKey()
          .equals(other.getLocKey());
      result = result && getSendToIDsList()
          .equals(other.getSendToIDsList());
      result = result && (getDataSize()
          == other.getDataSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERREAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getServerRead());
      hash = (37 * hash) + LOCKEY_FIELD_NUMBER;
      hash = (53 * hash) + getLocKey().hashCode();
      if (getSendToIDsCount() > 0) {
        hash = (37 * hash) + SENDTOIDS_FIELD_NUMBER;
        hash = (53 * hash) + getSendToIDsList().hashCode();
      }
      hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
      hash = (53 * hash) + getDataSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protopacks.PackFW.PackHeaderIn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderIn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderIn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderIn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protopacks.PackFW.PackHeaderIn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protopacks.PackHeaderIn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protopacks.PackHeaderIn)
        protopacks.PackFW.PackHeaderInOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderIn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderIn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protopacks.PackFW.PackHeaderIn.class, protopacks.PackFW.PackHeaderIn.Builder.class);
      }

      // Construct using protopacks.PackFW.PackHeaderIn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverRead_ = false;

        locKey_ = "";

        sendToIDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        dataSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderIn_descriptor;
      }

      public protopacks.PackFW.PackHeaderIn getDefaultInstanceForType() {
        return protopacks.PackFW.PackHeaderIn.getDefaultInstance();
      }

      public protopacks.PackFW.PackHeaderIn build() {
        protopacks.PackFW.PackHeaderIn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protopacks.PackFW.PackHeaderIn buildPartial() {
        protopacks.PackFW.PackHeaderIn result = new protopacks.PackFW.PackHeaderIn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.serverRead_ = serverRead_;
        result.locKey_ = locKey_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sendToIDs_ = java.util.Collections.unmodifiableList(sendToIDs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sendToIDs_ = sendToIDs_;
        result.dataSize_ = dataSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protopacks.PackFW.PackHeaderIn) {
          return mergeFrom((protopacks.PackFW.PackHeaderIn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protopacks.PackFW.PackHeaderIn other) {
        if (other == protopacks.PackFW.PackHeaderIn.getDefaultInstance()) return this;
        if (other.getServerRead() != false) {
          setServerRead(other.getServerRead());
        }
        if (!other.getLocKey().isEmpty()) {
          locKey_ = other.locKey_;
          onChanged();
        }
        if (!other.sendToIDs_.isEmpty()) {
          if (sendToIDs_.isEmpty()) {
            sendToIDs_ = other.sendToIDs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSendToIDsIsMutable();
            sendToIDs_.addAll(other.sendToIDs_);
          }
          onChanged();
        }
        if (other.getDataSize() != 0) {
          setDataSize(other.getDataSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protopacks.PackFW.PackHeaderIn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protopacks.PackFW.PackHeaderIn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean serverRead_ ;
      /**
       * <code>bool serverRead = 1;</code>
       */
      public boolean getServerRead() {
        return serverRead_;
      }
      /**
       * <code>bool serverRead = 1;</code>
       */
      public Builder setServerRead(boolean value) {
        
        serverRead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool serverRead = 1;</code>
       */
      public Builder clearServerRead() {
        
        serverRead_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object locKey_ = "";
      /**
       * <code>string locKey = 2;</code>
       */
      public java.lang.String getLocKey() {
        java.lang.Object ref = locKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocKeyBytes() {
        java.lang.Object ref = locKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locKey = 2;</code>
       */
      public Builder setLocKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        locKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string locKey = 2;</code>
       */
      public Builder clearLocKey() {
        
        locKey_ = getDefaultInstance().getLocKey();
        onChanged();
        return this;
      }
      /**
       * <code>string locKey = 2;</code>
       */
      public Builder setLocKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        locKey_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> sendToIDs_ = java.util.Collections.emptyList();
      private void ensureSendToIDsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendToIDs_ = new java.util.ArrayList<java.lang.Integer>(sendToIDs_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getSendToIDsList() {
        return java.util.Collections.unmodifiableList(sendToIDs_);
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public int getSendToIDsCount() {
        return sendToIDs_.size();
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public int getSendToIDs(int index) {
        return sendToIDs_.get(index);
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public Builder setSendToIDs(
          int index, int value) {
        ensureSendToIDsIsMutable();
        sendToIDs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public Builder addSendToIDs(int value) {
        ensureSendToIDsIsMutable();
        sendToIDs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public Builder addAllSendToIDs(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSendToIDsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sendToIDs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 sendToIDs = 3;</code>
       */
      public Builder clearSendToIDs() {
        sendToIDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int dataSize_ ;
      /**
       * <code>uint32 dataSize = 4;</code>
       */
      public int getDataSize() {
        return dataSize_;
      }
      /**
       * <code>uint32 dataSize = 4;</code>
       */
      public Builder setDataSize(int value) {
        
        dataSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dataSize = 4;</code>
       */
      public Builder clearDataSize() {
        
        dataSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protopacks.PackHeaderIn)
    }

    // @@protoc_insertion_point(class_scope:protopacks.PackHeaderIn)
    private static final protopacks.PackFW.PackHeaderIn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protopacks.PackFW.PackHeaderIn();
    }

    public static protopacks.PackFW.PackHeaderIn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackHeaderIn>
        PARSER = new com.google.protobuf.AbstractParser<PackHeaderIn>() {
      public PackHeaderIn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PackHeaderIn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackHeaderIn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackHeaderIn> getParserForType() {
      return PARSER;
    }

    public protopacks.PackFW.PackHeaderIn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackHeaderOutOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protopacks.PackHeaderOut)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string locKey = 1;</code>
     */
    java.lang.String getLocKey();
    /**
     * <code>string locKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocKeyBytes();

    /**
     * <code>uint32 sentFromID = 2;</code>
     */
    int getSentFromID();

    /**
     * <code>uint32 dataSize = 3;</code>
     */
    int getDataSize();
  }
  /**
   * Protobuf type {@code protopacks.PackHeaderOut}
   */
  public  static final class PackHeaderOut extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protopacks.PackHeaderOut)
      PackHeaderOutOrBuilder {
    // Use PackHeaderOut.newBuilder() to construct.
    private PackHeaderOut(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackHeaderOut() {
      locKey_ = "";
      sentFromID_ = 0;
      dataSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PackHeaderOut(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              locKey_ = s;
              break;
            }
            case 16: {

              sentFromID_ = input.readUInt32();
              break;
            }
            case 24: {

              dataSize_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protopacks.PackFW.internal_static_protopacks_PackHeaderOut_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protopacks.PackFW.internal_static_protopacks_PackHeaderOut_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protopacks.PackFW.PackHeaderOut.class, protopacks.PackFW.PackHeaderOut.Builder.class);
    }

    public static final int LOCKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object locKey_;
    /**
     * <code>string locKey = 1;</code>
     */
    public java.lang.String getLocKey() {
      java.lang.Object ref = locKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locKey_ = s;
        return s;
      }
    }
    /**
     * <code>string locKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocKeyBytes() {
      java.lang.Object ref = locKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTFROMID_FIELD_NUMBER = 2;
    private int sentFromID_;
    /**
     * <code>uint32 sentFromID = 2;</code>
     */
    public int getSentFromID() {
      return sentFromID_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int dataSize_;
    /**
     * <code>uint32 dataSize = 3;</code>
     */
    public int getDataSize() {
      return dataSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, locKey_);
      }
      if (sentFromID_ != 0) {
        output.writeUInt32(2, sentFromID_);
      }
      if (dataSize_ != 0) {
        output.writeUInt32(3, dataSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, locKey_);
      }
      if (sentFromID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sentFromID_);
      }
      if (dataSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, dataSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protopacks.PackFW.PackHeaderOut)) {
        return super.equals(obj);
      }
      protopacks.PackFW.PackHeaderOut other = (protopacks.PackFW.PackHeaderOut) obj;

      boolean result = true;
      result = result && getLocKey()
          .equals(other.getLocKey());
      result = result && (getSentFromID()
          == other.getSentFromID());
      result = result && (getDataSize()
          == other.getDataSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCKEY_FIELD_NUMBER;
      hash = (53 * hash) + getLocKey().hashCode();
      hash = (37 * hash) + SENTFROMID_FIELD_NUMBER;
      hash = (53 * hash) + getSentFromID();
      hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
      hash = (53 * hash) + getDataSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protopacks.PackFW.PackHeaderOut parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderOut parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderOut parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackHeaderOut parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protopacks.PackFW.PackHeaderOut prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protopacks.PackHeaderOut}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protopacks.PackHeaderOut)
        protopacks.PackFW.PackHeaderOutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderOut_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderOut_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protopacks.PackFW.PackHeaderOut.class, protopacks.PackFW.PackHeaderOut.Builder.class);
      }

      // Construct using protopacks.PackFW.PackHeaderOut.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        locKey_ = "";

        sentFromID_ = 0;

        dataSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protopacks.PackFW.internal_static_protopacks_PackHeaderOut_descriptor;
      }

      public protopacks.PackFW.PackHeaderOut getDefaultInstanceForType() {
        return protopacks.PackFW.PackHeaderOut.getDefaultInstance();
      }

      public protopacks.PackFW.PackHeaderOut build() {
        protopacks.PackFW.PackHeaderOut result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protopacks.PackFW.PackHeaderOut buildPartial() {
        protopacks.PackFW.PackHeaderOut result = new protopacks.PackFW.PackHeaderOut(this);
        result.locKey_ = locKey_;
        result.sentFromID_ = sentFromID_;
        result.dataSize_ = dataSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protopacks.PackFW.PackHeaderOut) {
          return mergeFrom((protopacks.PackFW.PackHeaderOut)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protopacks.PackFW.PackHeaderOut other) {
        if (other == protopacks.PackFW.PackHeaderOut.getDefaultInstance()) return this;
        if (!other.getLocKey().isEmpty()) {
          locKey_ = other.locKey_;
          onChanged();
        }
        if (other.getSentFromID() != 0) {
          setSentFromID(other.getSentFromID());
        }
        if (other.getDataSize() != 0) {
          setDataSize(other.getDataSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protopacks.PackFW.PackHeaderOut parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protopacks.PackFW.PackHeaderOut) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object locKey_ = "";
      /**
       * <code>string locKey = 1;</code>
       */
      public java.lang.String getLocKey() {
        java.lang.Object ref = locKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocKeyBytes() {
        java.lang.Object ref = locKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locKey = 1;</code>
       */
      public Builder setLocKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        locKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string locKey = 1;</code>
       */
      public Builder clearLocKey() {
        
        locKey_ = getDefaultInstance().getLocKey();
        onChanged();
        return this;
      }
      /**
       * <code>string locKey = 1;</code>
       */
      public Builder setLocKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        locKey_ = value;
        onChanged();
        return this;
      }

      private int sentFromID_ ;
      /**
       * <code>uint32 sentFromID = 2;</code>
       */
      public int getSentFromID() {
        return sentFromID_;
      }
      /**
       * <code>uint32 sentFromID = 2;</code>
       */
      public Builder setSentFromID(int value) {
        
        sentFromID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sentFromID = 2;</code>
       */
      public Builder clearSentFromID() {
        
        sentFromID_ = 0;
        onChanged();
        return this;
      }

      private int dataSize_ ;
      /**
       * <code>uint32 dataSize = 3;</code>
       */
      public int getDataSize() {
        return dataSize_;
      }
      /**
       * <code>uint32 dataSize = 3;</code>
       */
      public Builder setDataSize(int value) {
        
        dataSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dataSize = 3;</code>
       */
      public Builder clearDataSize() {
        
        dataSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protopacks.PackHeaderOut)
    }

    // @@protoc_insertion_point(class_scope:protopacks.PackHeaderOut)
    private static final protopacks.PackFW.PackHeaderOut DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protopacks.PackFW.PackHeaderOut();
    }

    public static protopacks.PackFW.PackHeaderOut getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackHeaderOut>
        PARSER = new com.google.protobuf.AbstractParser<PackHeaderOut>() {
      public PackHeaderOut parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PackHeaderOut(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackHeaderOut> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackHeaderOut> getParserForType() {
      return PARSER;
    }

    public protopacks.PackFW.PackHeaderOut getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackA0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protopacks.PackA0)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code protopacks.PackA0}
   */
  public  static final class PackA0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protopacks.PackA0)
      PackA0OrBuilder {
    // Use PackA0.newBuilder() to construct.
    private PackA0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackA0() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PackA0(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protopacks.PackFW.internal_static_protopacks_PackA0_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protopacks.PackFW.internal_static_protopacks_PackA0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protopacks.PackFW.PackA0.class, protopacks.PackFW.PackA0.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protopacks.PackFW.PackA0)) {
        return super.equals(obj);
      }
      protopacks.PackFW.PackA0 other = (protopacks.PackFW.PackA0) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protopacks.PackFW.PackA0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackA0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackA0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackA0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackA0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackA0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackA0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protopacks.PackFW.PackA0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protopacks.PackA0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protopacks.PackA0)
        protopacks.PackFW.PackA0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protopacks.PackFW.internal_static_protopacks_PackA0_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protopacks.PackFW.internal_static_protopacks_PackA0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protopacks.PackFW.PackA0.class, protopacks.PackFW.PackA0.Builder.class);
      }

      // Construct using protopacks.PackFW.PackA0.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protopacks.PackFW.internal_static_protopacks_PackA0_descriptor;
      }

      public protopacks.PackFW.PackA0 getDefaultInstanceForType() {
        return protopacks.PackFW.PackA0.getDefaultInstance();
      }

      public protopacks.PackFW.PackA0 build() {
        protopacks.PackFW.PackA0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protopacks.PackFW.PackA0 buildPartial() {
        protopacks.PackFW.PackA0 result = new protopacks.PackFW.PackA0(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protopacks.PackFW.PackA0) {
          return mergeFrom((protopacks.PackFW.PackA0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protopacks.PackFW.PackA0 other) {
        if (other == protopacks.PackFW.PackA0.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protopacks.PackFW.PackA0 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protopacks.PackFW.PackA0) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protopacks.PackA0)
    }

    // @@protoc_insertion_point(class_scope:protopacks.PackA0)
    private static final protopacks.PackFW.PackA0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protopacks.PackFW.PackA0();
    }

    public static protopacks.PackFW.PackA0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackA0>
        PARSER = new com.google.protobuf.AbstractParser<PackA0>() {
      public PackA0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PackA0(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackA0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackA0> getParserForType() {
      return PARSER;
    }

    public protopacks.PackFW.PackA0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackA1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protopacks.PackA1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 heroID = 2;</code>
     */
    int getHeroID();
  }
  /**
   * Protobuf type {@code protopacks.PackA1}
   */
  public  static final class PackA1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protopacks.PackA1)
      PackA1OrBuilder {
    // Use PackA1.newBuilder() to construct.
    private PackA1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackA1() {
      name_ = "";
      heroID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PackA1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              heroID_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protopacks.PackFW.internal_static_protopacks_PackA1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protopacks.PackFW.internal_static_protopacks_PackA1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protopacks.PackFW.PackA1.class, protopacks.PackFW.PackA1.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEROID_FIELD_NUMBER = 2;
    private int heroID_;
    /**
     * <code>uint32 heroID = 2;</code>
     */
    public int getHeroID() {
      return heroID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (heroID_ != 0) {
        output.writeUInt32(2, heroID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (heroID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, heroID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protopacks.PackFW.PackA1)) {
        return super.equals(obj);
      }
      protopacks.PackFW.PackA1 other = (protopacks.PackFW.PackA1) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getHeroID()
          == other.getHeroID());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEROID_FIELD_NUMBER;
      hash = (53 * hash) + getHeroID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protopacks.PackFW.PackA1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackA1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackA1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protopacks.PackFW.PackA1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protopacks.PackFW.PackA1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackA1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protopacks.PackFW.PackA1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protopacks.PackFW.PackA1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protopacks.PackFW.PackA1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protopacks.PackA1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protopacks.PackA1)
        protopacks.PackFW.PackA1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protopacks.PackFW.internal_static_protopacks_PackA1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protopacks.PackFW.internal_static_protopacks_PackA1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protopacks.PackFW.PackA1.class, protopacks.PackFW.PackA1.Builder.class);
      }

      // Construct using protopacks.PackFW.PackA1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        heroID_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protopacks.PackFW.internal_static_protopacks_PackA1_descriptor;
      }

      public protopacks.PackFW.PackA1 getDefaultInstanceForType() {
        return protopacks.PackFW.PackA1.getDefaultInstance();
      }

      public protopacks.PackFW.PackA1 build() {
        protopacks.PackFW.PackA1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protopacks.PackFW.PackA1 buildPartial() {
        protopacks.PackFW.PackA1 result = new protopacks.PackFW.PackA1(this);
        result.name_ = name_;
        result.heroID_ = heroID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protopacks.PackFW.PackA1) {
          return mergeFrom((protopacks.PackFW.PackA1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protopacks.PackFW.PackA1 other) {
        if (other == protopacks.PackFW.PackA1.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHeroID() != 0) {
          setHeroID(other.getHeroID());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protopacks.PackFW.PackA1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protopacks.PackFW.PackA1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int heroID_ ;
      /**
       * <code>uint32 heroID = 2;</code>
       */
      public int getHeroID() {
        return heroID_;
      }
      /**
       * <code>uint32 heroID = 2;</code>
       */
      public Builder setHeroID(int value) {
        
        heroID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 heroID = 2;</code>
       */
      public Builder clearHeroID() {
        
        heroID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protopacks.PackA1)
    }

    // @@protoc_insertion_point(class_scope:protopacks.PackA1)
    private static final protopacks.PackFW.PackA1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protopacks.PackFW.PackA1();
    }

    public static protopacks.PackFW.PackA1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackA1>
        PARSER = new com.google.protobuf.AbstractParser<PackA1>() {
      public PackA1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PackA1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackA1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackA1> getParserForType() {
      return PARSER;
    }

    public protopacks.PackFW.PackA1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protopacks_PackHeaderIn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protopacks_PackHeaderIn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protopacks_PackHeaderOut_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protopacks_PackHeaderOut_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protopacks_PackA0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protopacks_PackA0_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protopacks_PackA1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protopacks_PackA1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PackFW.proto\022\nprotopacks\"W\n\014PackHeader" +
      "In\022\022\n\nserverRead\030\001 \001(\010\022\016\n\006locKey\030\002 \001(\t\022\021" +
      "\n\tsendToIDs\030\003 \003(\r\022\020\n\010dataSize\030\004 \001(\r\"E\n\rP" +
      "ackHeaderOut\022\016\n\006locKey\030\001 \001(\t\022\022\n\nsentFrom" +
      "ID\030\002 \001(\r\022\020\n\010dataSize\030\003 \001(\r\"\026\n\006PackA0\022\014\n\004" +
      "name\030\001 \001(\t\"&\n\006PackA1\022\014\n\004name\030\001 \001(\t\022\016\n\006he" +
      "roID\030\002 \001(\rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protopacks_PackHeaderIn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protopacks_PackHeaderIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protopacks_PackHeaderIn_descriptor,
        new java.lang.String[] { "ServerRead", "LocKey", "SendToIDs", "DataSize", });
    internal_static_protopacks_PackHeaderOut_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protopacks_PackHeaderOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protopacks_PackHeaderOut_descriptor,
        new java.lang.String[] { "LocKey", "SentFromID", "DataSize", });
    internal_static_protopacks_PackA0_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protopacks_PackA0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protopacks_PackA0_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_protopacks_PackA1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protopacks_PackA1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protopacks_PackA1_descriptor,
        new java.lang.String[] { "Name", "HeroID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
